title: கனவு
tagline: என் வாழ்வென்னும் பயணத்தில்...
url: https://tamil.smileprem.com
#logo: add-some-logo-here
copyright: பொதுவுடைமை @ 2009.

author: பிரேம்குமார் மாசிலாமணி
email: xxx@xxx.xxx
mobile: xxx-xxx-xxxx

social:
  name: பிரேம்குமார் மாசிலாமணி
  links:
    - https://www.linkedin.com/in/premkumarmasilamani
    - https://github.com/smileprem

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 150

permalink: /:title/

img-path: https://tamil.smileprem.com/public/images
download-path: https://tamil.smileprem.com/public/downloads

newsletter: https://eepurl.com/dE1xBb
contact-form: https://www.emailmeform.com/builder/form/CVTAEonS7L1fvW4H0b8
english-blog: https://blog.smileprem.com/
english-podcast: https://podcast.smileprem.com/

donation: https://www.blockchain.com/btc/address/14hjWY7QzpD5mjPhmYs8FHrm3aJiEKX82s
