title: கனவு
tagline: என் வாழ்வென்னும் பயணத்தில்...
url: http://localhost:4000
#logo: add-some-logo-here
copyright: பொதுவுடைமை @ 2009.

author: பிரேம்குமார் மாசிலாமணி
email: premkumar.masilamani.2020@gmail.com
mobile: xxx-xxx-xxxx

social:
  name: பிரேம்குமார் மாசிலாமணி
  links:
    - https://www.linkedin.com/in/premkumarmasilamani
    - https://github.com/smileprem

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

permalink: /:title/

img-path: http://localhost:4000/public/images
download-path: http://localhost:4000/public/downloads

newsletter: http://eepurl.com/dE1xBb

home-page-url: https://www.smileprem.com
software-architect-url: https://www.linkedin.com/in/premkumarmasilamani
english-blog-url: https://blog.smileprem.com/
tamil-blog-url: https://tamil.smileprem.com/
life-coach-url: https://calendly.com/coachprem/life-coaching